# INI file
instance_name = grafana_ChVV

---

# Corresponding environment variables
GF_DEFAULT_INSTANCE_NAME=chernyshevvv_grafana
GF_SECURITY_ADMIN_USER=ChernyshevVV
GF_SECURITY_ADMIN_PASSWORD=netology