- name: Change system MOTD
  hosts: vms
  become: yes
  vars:
    custom_greeting: "Welcome to my SuperPuperDuper Linux system!"
  
  tasks:
    - name: Update MOTD with custom greeting
      copy:
        content: "{{ custom_greeting }}"
        dest: /etc/motd
        mode: '0644'
