- name: Change system MOTD with host info and greeting
  hosts: vms
  become: yes
  vars:
    admin_greeting: "Have a great day, dear sysadmin!"

  tasks:
    - name: Update MOTD with IP, hostname, and greeting
      copy:
        content: |
          Host: {{ ansible_hostname }}
          IP: {{ ansible_host }}
          {{ admin_greeting }}
        dest: /etc/motd
        mode: '0644'
