- name: Download and extract Kafka archive
  hosts: vms
  become: yes
  tasks:
    - name: Create directory for Kafka
      file:
        path: /opt/kafka
        state: directory
        mode: '0755'

    - name: Download Kafka binary archive
      get_url:
        url: https://archive.apache.org/dist/kafka/3.9.0/kafka_2.12-3.9.0.tgz
        dest: /tmp/kafka_2.12-3.9.0.tgz
        mode: '0644'

    - name: Extract Kafka archive
      unarchive:
        src: /tmp/kafka_2.12-3.9.0.tgz
        dest: /opt/kafka
        remote_src: yes
